import { Endpoint, EndpointDetail, FleetMetrics, CollectorGateway, VaultCredentialSummary, ScanJob, SecurityAuditLog } from "./types";

export const MOCK_METRICS: FleetMetrics = {
  total_endpoints: 24,
  online_endpoints: 22,
  bitlocker_rate: 95.8,
  tpm_rate: 100.0,
  defender_rate: 100.0,
  average_compliance: 94.2,
  active_gateways: 2,
  total_gateways: 2,
  critical_issues_count: 1,
};

export const MOCK_ENDPOINTS: Endpoint[] = [
  {
    id: "host-w11-exec-01",
    hostname: "W11-EXEC-LP04",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.1.42",
    mac_address: "00:1A:2B:3C:4D:5E",
    os_name: "Microsoft Windows 11 Enterprise 23H2",
    os_build: "22631.3296",
    serial_number: "8XKJ9201",
    manufacturer: "Dell Inc.",
    model: "Latitude 7440",
    chassis_type: "Laptop",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 94.5,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "host-ws22-dc-01",
    hostname: "DC01-PROD-EAST",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.2.10",
    mac_address: "52:54:00:12:34:56",
    os_name: "Microsoft Windows Server 2022 Datacenter",
    os_build: "20348.2407",
    serial_number: "VMware-56 4d 8a 91",
    manufacturer: "VMware, Inc.",
    model: "VMware7,1",
    chassis_type: "Server",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 98.0,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "host-w11-eng-09",
    hostname: "W11-ENG-WS09",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.1.77",
    mac_address: "A4:BB:6D:88:12:34",
    os_name: "Microsoft Windows 11 Pro 23H2",
    os_build: "22631.3007",
    serial_number: "PF4982A1",
    manufacturer: "Lenovo",
    model: "ThinkPad P16 Gen 2",
    chassis_type: "Laptop",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 88.0,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 250000000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "host-ws25-sql-02",
    hostname: "SQL02-PROD-CLUSTER",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.2.22",
    mac_address: "00:50:56:A1:B2:C3",
    os_name: "Microsoft Windows Server 2025 Datacenter Preview",
    os_build: "26100.1150",
    serial_number: "VMware-42 11 aa 09",
    manufacturer: "VMware, Inc.",
    model: "VMware7,1",
    chassis_type: "Server",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 100.0,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 300000000).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const MOCK_GATEWAYS: CollectorGateway[] = [
  {
    id: "gw-10-100-1-0",
    gateway_code: "gw-subnet-10-100-1-0",
    name: "On-Prem Corporate HQ (Subnet A)",
    subnet_cidr: "10.100.1.0/24",
    mtls_cert_fingerprint: "SHA256:4a8f9b2c3d1e5a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
    status: "healthy",
    version: "v1.2.4",
    latency_ms: 4,
    last_heartbeat_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "gw-10-100-2-0",
    gateway_code: "gw-subnet-10-100-2-0",
    name: "Datacenter East Racks (Subnet B)",
    subnet_cidr: "10.100.2.0/24",
    mtls_cert_fingerprint: "SHA256:9b2c3d1e5a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b4a8f",
    status: "healthy",
    version: "v1.2.4",
    latency_ms: 2,
    last_heartbeat_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 250000000).toISOString(),
  }
];

export const MOCK_CREDENTIALS: VaultCredentialSummary[] = [
  {
    id: "cred-1",
    opaque_id: "sec_ref_winrm_domain_prod_01",
    name: "Active Directory Domain Scan Account (gMSA)",
    credential_type: "domain_kerberos",
    domain_or_host: "CORP.ENDPOINTGUARD.LOCAL",
    username: "svc_endpointguard_winrm",
    created_at: new Date(Date.now() - 360000000).toISOString(),
    updated_at: new Date(Date.now() - 360000000).toISOString(),
  },
  {
    id: "cred-2",
    opaque_id: "sec_ref_bmc_snmpv3_dc_01",
    name: "Datacenter BMC/iLO SNMPv3 Auth Profile",
    credential_type: "snmp_v3",
    domain_or_host: "10.100.2.0/24",
    username: "sec_admin_snmp",
    created_at: new Date(Date.now() - 400000000).toISOString(),
    updated_at: new Date(Date.now() - 400000000).toISOString(),
  }
];

export const MOCK_SCANS: ScanJob[] = [
  {
    id: "scan-job-01",
    name: "HQ Subnet A - Full Hardware & CIS Audit",
    target_cidr: "10.100.1.0/24",
    scan_profile: "full_hardware_os",
    protocol: "winrm_https",
    vault_secret_ref: "sec_ref_winrm_domain_prod_01",
    gateway_id: "gw-10-100-1-0",
    status: "completed",
    total_hosts: 42,
    scanned_hosts: 42,
    compliant_hosts: 40,
    failed_hosts: 2,
    logs: [
      "[2026-08-09T17:00:00Z] [INFO] Authenticating to Subnet Gateway gw-subnet-10-100-1-0 via mTLS 1.3",
      "[2026-08-09T17:00:02Z] [INFO] Resolved opaque credential sec_ref_winrm_domain_prod_01 from Vault memory buffer",
      "[2026-08-09T17:00:05Z] [INFO] Probing 42 target hosts across 10.100.1.0/24 over WinRM HTTPS (Port 5986)",
      "[2026-08-09T17:00:30Z] [INFO] Batch WQL CIM queries executed successfully for Win32_OperatingSystem, Win32_Processor, Win32_DiskDrive",
      "[2026-08-09T17:01:00Z] [INFO] Querying Root\\CIMv2\\Security\\MicrosoftVolumeEncryption (BitLocker) and TPM 2.0 classes",
      "[2026-08-09T17:01:30Z] [INFO] Evaluating telemetry against CIS Windows 11 Benchmark v3.0.0",
      "[2026-08-09T17:02:15Z] [INFO] Scan completed successfully. 40/42 hosts compliant (95.2%).",
    ],
    started_at: new Date(Date.now() - 900000).toISOString(),
    completed_at: new Date(Date.now() - 720000).toISOString(),
    created_at: new Date(Date.now() - 900000).toISOString(),
  }
];

export const MOCK_AUDIT_LOGS: SecurityAuditLog[] = [
  {
    id: "log-1",
    correlation_id: "req-c83921fa",
    timestamp: new Date(Date.now() - 120000).toISOString(),
    actor: "sec_admin_ops",
    action: "SCAN_JOB_LAUNCHED",
    resource_type: "scan_job",
    resource_id: "scan-job-01",
    status: "SUCCESS",
    ip_address: "10.100.1.15",
    details: { target_cidr: "10.100.1.0/24", profile: "full_hardware_os" },
  },
  {
    id: "log-2",
    correlation_id: "req-f9821a00",
    timestamp: new Date(Date.now() - 360000).toISOString(),
    actor: "sec_admin_ops",
    action: "VAULT_CREDENTIAL_ENCRYPTED_AND_SAVED",
    resource_type: "vault_credential",
    resource_id: "sec_ref_winrm_domain_prod_01",
    status: "SUCCESS",
    ip_address: "10.100.1.15",
    details: { algorithm: "AES-256-GCM", key_derivation: "HKDF-SHA256" },
  },
  {
    id: "log-3",
    correlation_id: "req-b21849dd",
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    actor: "system_bootstrap",
    action: "GATEWAY_MTLS_CERT_VERIFIED",
    resource_type: "collector_gateway",
    resource_id: "gw-subnet-10-100-1-0",
    status: "SUCCESS",
    ip_address: "10.100.1.2",
    details: { tls_version: "TLSv1.3", cipher: "TLS_AES_256_GCM_SHA384" },
  }
];
