import {
  Endpoint,
  FleetMetrics,
  CollectorGateway,
  VaultCredentialSummary,
  ScanJob,
  SecurityAuditLog,
  VulnerabilityFinding,
  DriftEvent,
  NetworkSubnet,
  ReportConfig,
  HostSnapshot,
  SnapshotDiffItem,
  CISResult,
} from "./types";

export const MOCK_METRICS: FleetMetrics = {
  total_endpoints: 24,
  online_endpoints: 22,
  bitlocker_rate: 95.8,
  tpm_rate: 100.0,
  defender_rate: 100.0,
  average_compliance: 92.4,
  active_gateways: 2,
  total_gateways: 2,
  critical_issues_count: 3,
  open_critical_vulns: 4,
  open_kev_count: 2,
  compliance_bands: {
    band_90_100: 16,
    band_75_89: 5,
    band_50_74: 2,
    band_under_50: 1,
  },
};

export const MOCK_ENDPOINTS: Endpoint[] = [
  {
    id: "host-w11-exec-01",
    hostname: "W11-EXEC-LP04",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.1.42",
    mac_address: "00:1A:2B:3C:4D:5E",
    os_name: "Microsoft Windows 11 Enterprise 23H2",
    os_build: "22631.3296",
    serial_number: "8XKJ9201",
    manufacturer: "Dell Inc.",
    model: "Latitude 7440",
    chassis_type: "Laptop",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 96.5,
    open_vulns_count: 2,
    critical_vulns_count: 1,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "host-ws22-dc-01",
    hostname: "DC01-PROD-EAST",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.2.10",
    mac_address: "52:54:00:12:34:56",
    os_name: "Microsoft Windows Server 2022 Datacenter",
    os_build: "20348.2407",
    serial_number: "VMware-56 4d 8a 91",
    manufacturer: "VMware, Inc.",
    model: "VMware7,1",
    chassis_type: "Server",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 98.0,
    open_vulns_count: 0,
    critical_vulns_count: 0,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "host-w11-eng-09",
    hostname: "W11-ENG-WS09",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.1.77",
    mac_address: "A4:BB:6D:88:12:34",
    os_name: "Microsoft Windows 11 Pro 23H2",
    os_build: "22631.3007",
    serial_number: "PF4982A1",
    manufacturer: "Lenovo",
    model: "ThinkPad P16 Gen 2",
    chassis_type: "Laptop",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 84.0,
    open_vulns_count: 3,
    critical_vulns_count: 1,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 250000000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "host-ws25-sql-02",
    hostname: "SQL02-PROD-CLUSTER",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.2.22",
    mac_address: "00:50:56:A1:B2:C3",
    os_name: "Microsoft Windows Server 2025 Datacenter Preview",
    os_build: "26100.1150",
    serial_number: "VMware-42 11 aa 09",
    manufacturer: "VMware, Inc.",
    model: "VMware7,1",
    chassis_type: "Server",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 100.0,
    open_vulns_count: 0,
    critical_vulns_count: 0,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 300000000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "host-w11-finance-03",
    hostname: "W11-FIN-LT03",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.1.88",
    mac_address: "C8:4B:D6:99:88:77",
    os_name: "Microsoft Windows 11 Enterprise 22H2",
    os_build: "22621.2428",
    serial_number: "5CD93810AZ",
    manufacturer: "HP Inc.",
    model: "EliteBook 840 G10",
    chassis_type: "Laptop",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 68.5,
    open_vulns_count: 4,
    critical_vulns_count: 2,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 400000000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "host-w10-legacy-01",
    hostname: "W10-LEGACY-DEV",
    domain: "CORP.ENDPOINTGUARD.LOCAL",
    ip_address: "10.100.1.199",
    mac_address: "B0:7D:64:11:22:33",
    os_name: "Microsoft Windows 10 Pro 21H2",
    os_build: "19044.1889",
    serial_number: "L34988019",
    manufacturer: "Dell Inc.",
    model: "OptiPlex 7070",
    chassis_type: "Desktop",
    status: "online",
    agentless_protocol: "winrm_https",
    compliance_score: 42.0,
    open_vulns_count: 7,
    critical_vulns_count: 3,
    last_scanned_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 500000000).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const MOCK_DRIFT_EVENTS: DriftEvent[] = [
  {
    id: "drift-001",
    tenant_id: "tenant-default-01",
    host_id: "host-w11-eng-09",
    hostname: "W11-ENG-WS09",
    subsystem: "SecurityBaseline",
    property_name: "BitLocker.VolumeC.ProtectionStatus",
    old_value: "1 (Protected)",
    new_value: "0 (Decrypted/Disabled)",
    severity: "CRITICAL",
    acknowledged: false,
    detected_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "drift-002",
    tenant_id: "tenant-default-01",
    host_id: "host-w11-finance-03",
    hostname: "W11-FIN-LT03",
    subsystem: "LocalAccounts",
    property_name: "Administrators.Members",
    old_value: '["CORP\\\\Domain Admins", "CORP\\\\EndpointGuardAdmin"]',
    new_value: '["CORP\\\\Domain Admins", "CORP\\\\EndpointGuardAdmin", "LocalBackupUser"]',
    severity: "CRITICAL",
    acknowledged: false,
    detected_at: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: "drift-003",
    tenant_id: "tenant-default-01",
    host_id: "host-w11-exec-01",
    hostname: "W11-EXEC-LP04",
    subsystem: "Memory",
    property_name: "Memory.TotalCapacityBytes",
    old_value: "17179869184 (16 GB)",
    new_value: "34359738368 (32 GB)",
    severity: "WARNING",
    acknowledged: true,
    detected_at: new Date(Date.now() - 180 * 60000).toISOString(),
  },
  {
    id: "drift-004",
    tenant_id: "tenant-default-01",
    host_id: "host-ws22-dc-01",
    hostname: "DC01-PROD-EAST",
    subsystem: "Firmware",
    property_name: "BIOS.Version",
    old_value: "1.14.0",
    new_value: "1.15.2",
    severity: "INFO",
    acknowledged: true,
    detected_at: new Date(Date.now() - 360 * 60000).toISOString(),
  },
];

export const MOCK_VULNERABILITIES: VulnerabilityFinding[] = [
  {
    id: "vuln-001",
    tenant_id: "tenant-default-01",
    endpoint_id: "host-w11-exec-01",
    hostname: "W11-EXEC-LP04",
    cve_id: "CVE-2024-38077",
    cpe_string: "cpe:2.3:o:microsoft:windows_11_23h2:-:*:*:*:*:*:*:*",
    cvss_score: 9.8,
    severity: "CRITICAL",
    is_kev: true,
    kev_due_date: "2026-08-25",
    short_description: "Windows Remote Desktop Licensing Service Remote Code Execution Vulnerability",
    status: "OPEN",
    remediation_guidance: "Apply Microsoft Security Update KB5040442 immediately or disable RDP Licensing service.",
    first_seen: new Date(Date.now() - 86400000).toISOString(),
    last_seen: new Date().toISOString(),
  },
  {
    id: "vuln-002",
    tenant_id: "tenant-default-01",
    endpoint_id: "host-w11-eng-09",
    hostname: "W11-ENG-WS09",
    cve_id: "CVE-2023-36884",
    cpe_string: "cpe:2.3:a:microsoft:office:2021:*:*:*:*:*:*:*",
    cvss_score: 8.8,
    severity: "HIGH",
    is_kev: true,
    kev_due_date: "2026-08-20",
    short_description: "Office and Windows HTML Remote Code Execution Vulnerability (RomCom RAT)",
    status: "OPEN",
    remediation_guidance: "Set BlockOfficeCreateProcess registry key under Defender ASR rules.",
    first_seen: new Date(Date.now() - 172800000).toISOString(),
    last_seen: new Date().toISOString(),
  },
  {
    id: "vuln-003",
    tenant_id: "tenant-default-01",
    endpoint_id: "host-w11-finance-03",
    hostname: "W11-FIN-LT03",
    cve_id: "CVE-2024-21412",
    cpe_string: "cpe:2.3:a:microsoft:windows_smartscreen:-:*:*:*:*:*:*:*",
    cvss_score: 8.1,
    severity: "HIGH",
    is_kev: false,
    short_description: "Microsoft Windows SmartScreen Security Feature Bypass Vulnerability",
    status: "OPEN",
    remediation_guidance: "Deploy monthly cumulative security update KB5034765.",
    first_seen: new Date(Date.now() - 250000000).toISOString(),
    last_seen: new Date().toISOString(),
  },
  {
    id: "vuln-004",
    tenant_id: "tenant-default-01",
    endpoint_id: "host-w10-legacy-01",
    hostname: "W10-LEGACY-DEV",
    cve_id: "CVE-2024-30078",
    cpe_string: "cpe:2.3:o:microsoft:windows_10_21h2:-:*:*:*:*:*:*:*",
    cvss_score: 8.8,
    severity: "HIGH",
    is_kev: false,
    short_description: "Windows Wi-Fi Driver Remote Code Execution Vulnerability",
    status: "OPEN",
    remediation_guidance: "Upgrade system to supported OS build and install Wi-Fi driver patch.",
    first_seen: new Date(Date.now() - 400000000).toISOString(),
    last_seen: new Date().toISOString(),
  }
];

export const MOCK_CIS_RESULTS: CISResult[] = [
  {
    id: "cis-001",
    endpoint_id: "host-w11-exec-01",
    benchmark_name: "CIS Microsoft Windows 11 Enterprise Benchmark v2.0.0",
    benchmark_level: "Level 1 (Corporate)",
    rule_id: "cis_18_1_1_1",
    rule_title: "Ensure 'UEFI Secure Boot' is enabled",
    category: "Firmware & Boot",
    status: "PASS",
    actual_value: "SecureBootState=ON, UEFIMode=Native",
    expected_value: "SecureBootState=ON",
    rationale: "Secure Boot stops unauthorized firmware, operating systems, or UEFI drivers from loading during startup.",
    remediation_script: "Set-SecureBootUEFI -Enable $true",
    cis_control_citation: "CIS Control 18.1.1.1 (Level 1)",
    evaluated_at: new Date().toISOString(),
  },
  {
    id: "cis-002",
    endpoint_id: "host-w11-exec-01",
    benchmark_name: "CIS Microsoft Windows 11 Enterprise Benchmark v2.0.0",
    benchmark_level: "Level 1 (Corporate)",
    rule_id: "cis_18_1_2_1",
    rule_title: "Ensure 'TPM 2.0' is present and active",
    category: "Hardware Security",
    status: "PASS",
    actual_value: "TPM Version 2.0, Status=Ready",
    expected_value: "TPM Version 2.0",
    rationale: "TPM provides cryptographic hardware isolation for BitLocker keys and Credential Guard.",
    remediation_script: "Enable-TpmAutoProvisioning",
    cis_control_citation: "CIS Control 18.1.2.1 (Level 1)",
    evaluated_at: new Date().toISOString(),
  },
  {
    id: "cis-003",
    endpoint_id: "host-w11-eng-09",
    benchmark_name: "CIS Microsoft Windows 11 Enterprise Benchmark v2.0.0",
    benchmark_level: "Level 1 (Corporate)",
    rule_id: "cis_18_9_30_2",
    rule_title: "Ensure 'BitLocker Drive Encryption' cipher strength is XTS-AES 256-bit",
    category: "Data Protection",
    status: "FAIL",
    actual_value: "EncryptionMethod=XTS-AES 128-bit",
    expected_value: "EncryptionMethod=XTS-AES 256-bit",
    rationale: "256-bit key length provides quantum-resistant cryptographic margin against advanced brute-force.",
    remediation_script: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\FVE' -Name 'EncryptionMethodWithXtsOs' -Value 7",
    cis_control_citation: "CIS Control 18.9.30.2 (Level 1)",
    evaluated_at: new Date().toISOString(),
  },
  {
    id: "cis-004",
    endpoint_id: "host-w11-finance-03",
    benchmark_name: "CIS Microsoft Windows 11 Enterprise Benchmark v2.0.0",
    benchmark_level: "Level 1 (Corporate)",
    rule_id: "cis_9_1_1",
    rule_title: "Ensure Windows Firewall Domain Profile is Enabled and Blocking Inbound",
    category: "Network Defense",
    status: "FAIL",
    actual_value: "DomainProfile=Disabled",
    expected_value: "DomainProfile=Enabled, Inbound=Block",
    rationale: "Host firewall prevents lateral traversal and unauthenticated worm propagation.",
    remediation_script: "Set-NetFirewallProfile -Profile Domain -Enabled True -DefaultInboundAction Block",
    cis_control_citation: "CIS Control 9.1.1 (Level 1)",
    evaluated_at: new Date().toISOString(),
  },
  {
    id: "cis-005",
    endpoint_id: "host-w10-legacy-01",
    benchmark_name: "CIS Microsoft Windows 11 Enterprise Benchmark v2.0.0",
    benchmark_level: "Level 1 (Corporate)",
    rule_id: "cis_18_9_30_1",
    rule_title: "Ensure SMBv1 protocol driver is disabled",
    category: "System Services",
    status: "FAIL",
    actual_value: "SMB1Protocol=Enabled (State=Running)",
    expected_value: "SMB1Protocol=Disabled",
    rationale: "SMBv1 lacks modern integrity safeguards and is susceptible to EternalBlue / WannaCry exploits.",
    remediation_script: "Disable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol -NoRestart",
    cis_control_citation: "CIS Control 18.9.30.1 (Level 1)",
    evaluated_at: new Date().toISOString(),
  }
];

export const MOCK_SUBNETS: NetworkSubnet[] = [
  {
    id: "subnet-01",
    subnet_cidr: "10.100.1.0/24",
    name: "Corporate Workstations & Laptops (HQ)",
    location: "US-East (New York Data Center)",
    assigned_gateway_code: "gw-subnet-10-100-1-0",
    gateway_name: "Gateway HQ Subnet A",
    gateway_status: "healthy",
    gateway_latency_ms: 12,
    host_count: 18,
    online_count: 17,
    compliant_count: 15,
    last_scan_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: "subnet-02",
    subnet_cidr: "10.100.2.0/24",
    name: "Enterprise Core Servers & Active Directory",
    location: "US-East (Primary VPC)",
    assigned_gateway_code: "gw-subnet-10-100-2-0",
    gateway_name: "Gateway Server DMZ",
    gateway_status: "healthy",
    gateway_latency_ms: 8,
    host_count: 6,
    online_count: 6,
    compliant_count: 6,
    transport_protocol: "winrm_https",
    allow_insecure_http: false,
    last_scan_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: "subnet-03",
    subnet_cidr: "10.100.4.0/24",
    name: "Legacy Branch Office Lab (Unencrypted Override)",
    location: "US-West (Branch Office Lab)",
    assigned_gateway_code: "gw-subnet-10-100-4-0",
    gateway_name: "Gateway Branch Lab",
    gateway_status: "degraded",
    gateway_latency_ms: 145,
    host_count: 8,
    online_count: 8,
    compliant_count: 4,
    transport_protocol: "winrm_http",
    allow_insecure_http: true,
    last_scan_at: new Date(Date.now() - 45 * 60000).toISOString(),
  }
];

export const MOCK_REPORTS: ReportConfig[] = [
  {
    id: "rep-001",
    title: "Executive CISO Weekly Fleet Posture",
    report_type: "EXECUTIVE_SUMMARY",
    format: "PDF",
    schedule: "WEEKLY",
    recipients: ["ciso@corp.local", "secops-leads@corp.local"],
    shareable_token: "tok_shr_9a8b7c6d5e4f3a2b",
    shareable_url: "https://dashboard.endpointguard.local/reports/shared?token=tok_shr_9a8b7c6d5e4f3a2b",
    expires_at: new Date(Date.now() + 48 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    last_generated_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "rep-002",
    title: "CIS Windows 11 Benchmark Compliance Audit Evidence",
    report_type: "COMPLIANCE_AUDIT",
    format: "CSV",
    schedule: "DAILY",
    recipients: ["compliance-auditor@corp.local"],
    shareable_token: "tok_shr_1122334455667788",
    shareable_url: "https://dashboard.endpointguard.local/reports/shared?token=tok_shr_1122334455667788",
    expires_at: new Date(Date.now() + 24 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
    last_generated_at: new Date(Date.now() - 86400000).toISOString(),
  }
];

export const MOCK_SNAPSHOTS: HostSnapshot[] = [
  {
    id: "snap-w11-002",
    endpoint_id: "host-w11-exec-01",
    hostname: "W11-EXEC-LP04",
    scan_job_id: "job-scan-9902",
    payload_hash: "sha256:7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a",
    created_at: new Date().toISOString(),
    hardware: {
      endpoint_id: "host-w11-exec-01",
      cpu_details: {
        name: "13th Gen Intel(R) Core(TM) i7-1370P",
        architecture: "x64",
        sockets: 1,
        cores: 14,
        logical_processors: 20,
        max_clock_mhz: 5200,
        virtualization_firmware: true,
        vbs_status: "Running",
        hvci_status: "Enabled",
      },
      memory_details: {
        total_bytes: 34359738368,
        slots_used: 2,
        total_slots: 2,
        dimms: [
          { slot: "DIMM 1", capacity_bytes: 17179869184, speed_mhz: 5600, manufacturer: "SK Hynix", part_number: "HMCG78AGBUA081N" },
          { slot: "DIMM 2", capacity_bytes: 17179869184, speed_mhz: 5600, manufacturer: "SK Hynix", part_number: "HMCG78AGBUA081N" },
        ]
      },
      storage_details: {
        disks: [
          { index: 0, model: "NVMe KIOXIA 1024GB KXG80ZNV1T02", bus_type: "NVMe", size_bytes: 1024209543168, smart_status: "Healthy (100% Remaining)", serial: "13TPA019X" }
        ]
      },
      network_details: {
        adapters: [
          { name: "Intel(R) Wi-Fi 6E AX211 160MHz", mac: "00:1A:2B:3C:4D:5E", ip_addresses: ["10.100.1.42"], subnet_mask: "255.255.255.0", default_gateway: "10.100.1.1", dhcp_enabled: true, link_speed_mbps: 2400 }
        ]
      },
      bios_details: {
        vendor: "Dell Inc.",
        version: "1.15.2",
        release_date: "2026-03-12",
        smbios_version: "3.5",
        smbios_guid: "4C4C4544-0058-4B10-804A-B3C04F323031",
        manufacturer: "Dell Inc.",
        secure_boot: true,
        uefi_mode: true,
      },
      tpm_details: {
        present: true,
        spec_version: "2.0",
        manufacturer_id: "IFX (Infineon)",
        enabled: true,
        activated: true,
        pcr0_hash: "A8B7C6D5E4F3A2B10987654321ABCDEF0123456789ABCDEF0123456789ABCDEF",
        pcr7_hash: "112233445566778899AABBCCDDEEFF00112233445566778899AABBCCDDEEFF00",
      }
    },
    software: [
      { name: "Microsoft 365 Apps for enterprise", version: "16.0.17328.20184", vendor: "Microsoft Corporation" },
      { name: "Google Chrome", version: "125.0.6422.142", vendor: "Google LLC" },
      { name: "CrowdStrike Falcon Sensor", version: "7.14.18305.0", vendor: "CrowdStrike, Inc." },
      { name: "Microsoft Visual Studio Code", version: "1.89.1", vendor: "Microsoft Corporation" }
    ],
    security_posture: {
      endpoint_id: "host-w11-exec-01",
      bitlocker_status: {
        volumes: [
          { drive_letter: "C:", protection_status: 1, encryption_method: "XTS-AES 256-bit", lock_status: 0, key_protectors: ["Tpm", "NumericalPassword (RecoveryKey)"] }
        ]
      },
      defender_status: {
        realtime_enabled: true,
        cloud_protection: true,
        tamper_protection: true,
        antimalware_version: "4.18.24050.7",
        signatures_updated: "2026-08-09T22:00:00Z",
        pua_protection: true,
      },
      firewall_status: { domain_profile: true, private_profile: true, public_profile: true },
      uac_status: { admin_approval_mode: true },
      credential_guard_enabled: true,
      lsa_protection_enabled: true,
      smbv1_disabled: true,
      rdp_nla_required: true,
      hotfixes: [
        { hotfix_id: "KB5039212", description: "Security Update", installed_on: "2026-06-11" },
        { hotfix_id: "KB5040442", description: "Cumulative Security Update", installed_on: "2026-07-09" }
      ],
      local_admins: ["CORP\\Domain Admins", "CORP\\EndpointGuardAdmin"],
    },
    cis_results: MOCK_CIS_RESULTS,
  },
  {
    id: "snap-w11-001",
    endpoint_id: "host-w11-exec-01",
    hostname: "W11-EXEC-LP04",
    scan_job_id: "job-scan-9801",
    payload_hash: "sha256:1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b",
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    hardware: {
      endpoint_id: "host-w11-exec-01",
      cpu_details: {
        name: "13th Gen Intel(R) Core(TM) i7-1370P",
        architecture: "x64",
        sockets: 1,
        cores: 14,
        logical_processors: 20,
        max_clock_mhz: 5200,
        virtualization_firmware: true,
        vbs_status: "Running",
        hvci_status: "Enabled",
      },
      memory_details: {
        total_bytes: 17179869184,
        slots_used: 1,
        total_slots: 2,
        dimms: [
          { slot: "DIMM 1", capacity_bytes: 17179869184, speed_mhz: 5600, manufacturer: "SK Hynix", part_number: "HMCG78AGBUA081N" },
        ]
      },
      storage_details: {
        disks: [
          { index: 0, model: "NVMe KIOXIA 1024GB KXG80ZNV1T02", bus_type: "NVMe", size_bytes: 1024209543168, smart_status: "Healthy", serial: "13TPA019X" }
        ]
      },
      network_details: {
        adapters: [
          { name: "Intel(R) Wi-Fi 6E AX211 160MHz", mac: "00:1A:2B:3C:4D:5E", ip_addresses: ["10.100.1.42"], subnet_mask: "255.255.255.0", default_gateway: "10.100.1.1", dhcp_enabled: true, link_speed_mbps: 2400 }
        ]
      },
      bios_details: {
        vendor: "Dell Inc.",
        version: "1.14.0",
        release_date: "2025-11-20",
        smbios_version: "3.5",
        smbios_guid: "4C4C4544-0058-4B10-804A-B3C04F323031",
        manufacturer: "Dell Inc.",
        secure_boot: true,
        uefi_mode: true,
      },
      tpm_details: {
        present: true,
        spec_version: "2.0",
        manufacturer_id: "IFX (Infineon)",
        enabled: true,
        activated: true,
        pcr0_hash: "A8B7C6D5E4F3A2B10987654321ABCDEF0123456789ABCDEF0123456789ABCDEF",
        pcr7_hash: "112233445566778899AABBCCDDEEFF00112233445566778899AABBCCDDEEFF00",
      }
    },
    software: [
      { name: "Microsoft 365 Apps for enterprise", version: "16.0.17328.20184", vendor: "Microsoft Corporation" },
      { name: "Google Chrome", version: "124.0.6367.208", vendor: "Google LLC" },
      { name: "CrowdStrike Falcon Sensor", version: "7.14.18305.0", vendor: "CrowdStrike, Inc." }
    ],
    security_posture: {
      endpoint_id: "host-w11-exec-01",
      bitlocker_status: {
        volumes: [
          { drive_letter: "C:", protection_status: 1, encryption_method: "XTS-AES 256-bit", lock_status: 0, key_protectors: ["Tpm"] }
        ]
      },
      defender_status: {
        realtime_enabled: true,
        cloud_protection: true,
        tamper_protection: true,
        antimalware_version: "4.18.24040.4",
        signatures_updated: "2026-08-02T22:00:00Z",
        pua_protection: true,
      },
      firewall_status: { domain_profile: true, private_profile: true, public_profile: true },
      uac_status: { admin_approval_mode: true },
      credential_guard_enabled: true,
      lsa_protection_enabled: true,
      smbv1_disabled: true,
      rdp_nla_required: true,
      hotfixes: [
        { hotfix_id: "KB5039212", description: "Security Update", installed_on: "2026-06-11" }
      ],
      local_admins: ["CORP\\Domain Admins", "CORP\\EndpointGuardAdmin"],
    },
    cis_results: MOCK_CIS_RESULTS,
  }
];

export const MOCK_DIFF_EXAMPLE: SnapshotDiffItem[] = [
  {
    subsystem: "Memory",
    field_path: "memory_details.total_bytes",
    old_value: "17,179,869,184 (16 GB)",
    new_value: "34,359,738,368 (32 GB)",
    severity: "WARNING",
    change_type: "MODIFIED",
  },
  {
    subsystem: "Memory",
    field_path: "memory_details.dimms[1]",
    old_value: "None (Empty Slot)",
    new_value: "DIMM 2: 16 GB SK Hynix DDR5-5600",
    severity: "WARNING",
    change_type: "ADDED",
  },
  {
    subsystem: "Firmware",
    field_path: "bios_details.version",
    old_value: "1.14.0 (2025-11-20)",
    new_value: "1.15.2 (2026-03-12)",
    severity: "INFO",
    change_type: "MODIFIED",
  },
  {
    subsystem: "Software",
    field_path: "software[3]",
    old_value: "None",
    new_value: "Microsoft Visual Studio Code v1.89.1",
    severity: "INFO",
    change_type: "ADDED",
  },
  {
    subsystem: "SecurityBaseline",
    field_path: "security_posture.hotfixes[1]",
    old_value: "None",
    new_value: "KB5040442 (Cumulative Security Update)",
    severity: "INFO",
    change_type: "ADDED",
  }
];

export const MOCK_GATEWAYS: CollectorGateway[] = [
  {
    id: "gw-10-100-1-0",
    gateway_code: "gw-subnet-10-100-1-0",
    name: "On-Prem Corporate HQ (Subnet A)",
    subnet_cidr: "10.100.1.0/24",
    mtls_cert_fingerprint: "SHA256:4a8f9b2c3d1e5a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
    status: "healthy",
    version: "v1.4.2",
    latency_ms: 12,
    last_heartbeat_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "gw-10-100-2-0",
    gateway_code: "gw-subnet-10-100-2-0",
    name: "Primary VPC Server DMZ (Subnet B)",
    subnet_cidr: "10.100.2.0/24",
    mtls_cert_fingerprint: "SHA256:9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e",
    status: "healthy",
    version: "v1.4.2",
    latency_ms: 8,
    last_heartbeat_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
];
